#!/bin/bash

SCRIPTPATH="$(
    cd "$(dirname "$0")"
    pwd -P
)"
SRCPATH=$(
    cd ${SCRIPTPATH}/..
    pwd -P
)
if [ -f ${SCRIPTPATH}/_env.sh ]; then
    source ${SCRIPTPATH}/_env.sh
fi

CLANGD=${CLANGD:-clangd}
"${CLANGD}" $@
